version: '3.8'
services:
  feoptimisationenergie-app:
    image: helk1111/feoptimisationenergie
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://feoptimisationenergie-mysql:3306/feoptimisationenergie?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://feoptimisationenergie-mysql:3306/feoptimisationenergie?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - mynetwork

  feoptimisationenergie-mysql:
    image: mysql:8.0.30
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=feoptimisationenergie
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 127.0.0.1:8081:80
    environment:
      - PMA_HOST=feoptimisationenergie-mysql
      - PMA_PORT=3306
    networks:
      - mynetwork

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    networks:
      - mynetwork

  temperature-predictor:
    build: .
    depends_on:
      - feoptimisationenergie-mysql
    networks:
      - mynetwork

networks:
  mynetwork:
